steps:
- id: 'dockerBuild'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_APP_NAME}:${_VERSION}', '.' ]

substitutions:
  _VERSION: v0.3
  _REGION: us-central1
  _REPO_NAME: dev
  _APP_NAME: run-genai-client

images:
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_APP_NAME}:${_VERSION}'
