import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import '@/app/globals.css';
import Page from '@/components/page';

const LINKS = [
  {
    name: 'posts',
    route: '/posts',
  },
  {
    name: 'photos',
    route: '/photos',
  },
];

const HEADER = {
  title: 'home',
};

const notoSans = Noto_Sans({
  subsets: ['latin'],
  weight: ['100', '300', '500', '700', '900'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        <Page header={HEADER} links={LINKS}>
          {children}
        </Page>
      </body>
    </html>
  );
}
