import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import { NextThemeProvider } from '@/components/nextThemeProvider';
import Page from '@/components/page';
import Switch from '@/components/switch';

import '@/app/globals.css';

const LINKS = [
  {
    name: 'posts',
    route: '/posts',
  },
  {
    name: 'photos',
    route: '/photos',
  },
];

const HEADER = {
  title: 'home',
};

const notoSans = Noto_Sans({
  subsets: ['latin'],
  weight: ['100', '300', '500', '700', '900'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={notoSans.className}>
        <NextThemeProvider>
          <Switch />
          <Page header={HEADER} links={LINKS}>
            {children}
          </Page>
        </NextThemeProvider>
      </body>
    </html>
  );
}
